---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: confluentic-control-centre-rel
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cp-helm-charts
      sourceRef:
        kind: GitRepository
        name: confluentic-control-centre
  interval: 30s
  targetNamespace: confluentic

